### ISSUE TITLE
关于MGI_CNN网络的一些问题

### ISSUE THREAD

**Issue by Itsanewday** [liuzwin98/Pulmonary-Nodule-Detection-Based-on-Deep-Learning#1]
作者你好，之前在CSDN上看到过你的博客，发现你曾使用过mgi_cnn用于肺结节假阳性抑制。我想问下这个网络你复现的结果与作者的相比差距大吗？是采用作者的开源的代码复现吗？我用pytorch复现时发现结果大约在0.7左右，远低于论文中的0.94，方便说一下技巧吗？谢谢

**Comment by liuzwin98** [comment]
你好，我当时用它做假阳性抑制的时候都没有用完整的数据集，也没有复现他的结果，只是拿来增加本科毕设的工作量。你如果要做这方面的研究建议去找找近几年MICCAI上的文章

**Comment by Itsanewday** [comment]
感谢回复！
祝好！



---原始邮件---
发件人: "Liu ***@***.***&gt;
发送时间: 2022年2月17日(周四) 上午10:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liuzwin98/Pulmonary-Nodule-Detection-Based-on-Deep-Learning] 关于MGI_CNN网络的一些问题 (Issue #1)




 
你好，我当时用它做假阳性抑制的时候都没有用完整的数据集，也没有复现他的结果，只是拿来增加本科毕设的工作量。你如果要做这方面的研究建议去找找近几年MICCAI上的文章
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BelieferQAQ** [comment]
> 作者你好，之前在CSDN上看到过你的博客，发现你曾使用过mgi_cnn用于肺结节假阳性抑制。我想问下这个网络你复现的结果与作者的相比差距大吗？是采用作者的开源的代码复现吗？我用pytorch复现时发现结果大约在0.7左右，远低于论文中的0.94，方便说一下技巧吗？谢谢

大佬您好，我也想用pytorch复现这个代码，请问可以加个联系方式交流下吗？十分感谢，QQ：318831418
